-- Auto-generated by theme-switcher
-- Do not edit manually

vim.opt.background = "dark"

-- Set colorscheme
vim.cmd.colorscheme("gruvbox")

-- Catppuccin flavor
if "" ~= "" and "gruvbox" == "catppuccin" then
    require("catppuccin").setup({ flavour = "" })
    vim.cmd.colorscheme("catppuccin")
end

-- Force bufferline to refresh its highlights after colorscheme loads
vim.defer_fn(function()
    pcall(function()
        local bufferline = require("bufferline")
        if bufferline and bufferline.setup then
            -- Trigger a refresh of bufferline highlights
            vim.cmd("doautocmd ColorScheme")
        end
    end)
end, 50)
