#!/bin/bash

# ============================================================================
# DOTFILES LINKING SCRIPT - Safe Stow Management
# ============================================================================
# This script safely links dotfiles using GNU Stow without destroying existing
# configs. It handles auto-generated files and checks for conflicts first.
# ============================================================================

DOTFILES_DIR="$HOME/dotfiles"

# Change to the dotfiles directory
cd "$DOTFILES_DIR" || { echo "❌ Dotfiles directory not found!"; exit 1; }

# ============================================================================
# Helper Functions
# ============================================================================

# Check if a file is managed by dotfiles (via direct symlink OR tree folding)
# Returns 0 if managed, 1 if not (safe to delete)
is_dotfiles_managed() {
    local file="$1"
    [ ! -e "$file" ] && return 1  # File doesn't exist

    local real_path
    real_path=$(realpath "$file" 2>/dev/null)

    # Check if the resolved path is inside the dotfiles directory
    [[ "$real_path" == "$DOTFILES_DIR"* ]] && return 0
    return 1
}

echo "🔍 Checking for conflicts..."

# ============================================================================
# Step 1: Handle Known Auto-Generated Files
# ============================================================================
# Some programs auto-generate default configs on first run. We need to remove
# these BEFORE stowing, or they'll block our symlinks.
#
# IMPORTANT: We use is_dotfiles_managed() to check if a file is already ours.
# This handles both direct symlinks AND stow's "tree folding" (directory symlinks).

# Atomically replace a path with a symlink to the dotfiles source. Uses
# `mv -T` (rename(2)) so there's no window where the target is missing —
# essential for files like hyprland.conf that Hyprland regenerates the
# instant they disappear (it watches via inotify and re-creates the stub
# faster than `rm` + `stow` can race).
atomic_symlink() {
    local source="$1"      # absolute path inside $DOTFILES_DIR
    local target="$2"      # absolute path in $HOME
    local tmp="${target}.linking.$$"
    mkdir -p "$(dirname "$target")"
    # Stow rejects absolute symlinks ("Ignoring an absolute symlink"), so use
    # a relative one that matches what stow itself would create.
    local rel
    rel=$(realpath --relative-to="$(dirname "$target")" "$source")
    ln -sfn "$rel" "$tmp"
    mv -Tf "$tmp" "$target"
}

# Pre-link known auto-generated files that race with stow. After this runs,
# stow sees an existing symlink pointing to the right place and accepts it
# during --restow.
cleanup_autogenerated() {
    # Hyprland regenerates hyprland.conf on inotify; pre-link it atomically.
    # Unconditional — also re-normalizes any stale absolute symlink from a
    # prior buggy run into the relative form stow expects.
    echo "  → Pre-linking Hyprland config (atomic, race-safe)"
    atomic_symlink "$DOTFILES_DIR/.config/hypr/hyprland.conf" "$HOME/.config/hypr/hyprland.conf"

    # Git's default .gitconfig — slow regen, plain delete is fine.
    if [ -f "$HOME/.gitconfig" ] && ! is_dotfiles_managed "$HOME/.gitconfig"; then
        echo "  → Removing auto-generated .gitconfig (dotfiles version will replace it)"
        rm -f "$HOME/.gitconfig"
    fi

    # xdg-mime / desktop apps can write a stub mimeapps.list before we link.
    if [ -f "$HOME/.config/mimeapps.list" ] && ! is_dotfiles_managed "$HOME/.config/mimeapps.list"; then
        echo "  → Removing auto-generated mimeapps.list"
        rm -f "$HOME/.config/mimeapps.list"
    fi
}

cleanup_autogenerated

# Add other known auto-generated files here as you discover them
# Use the is_dotfiles_managed function to safely check:
#
# if [ -f "$HOME/.config/someapp/config" ] && ! is_dotfiles_managed "$HOME/.config/someapp/config"; then
#     echo "  → Removing auto-generated someapp config"
#     rm -f "$HOME/.config/someapp/config"
# fi

# Explicitly remove .git symlink if it somehow got linked
if [ -L "$HOME/.git" ]; then
    rm "$HOME/.git"
    echo "  → Removed .git symlink from home directory"
fi

# ============================================================================
# Step 2: Dry-Run to Check for Remaining Conflicts
# ============================================================================
echo ""
echo "🧪 Running dry-run to check for conflicts..."

# Run dry-run and capture output
stow --simulate --restow -t ~ . > /tmp/stow_dryrun.log 2>&1

# Check for real conflicts (not just simulation mode warning).
# Note: this is informational only. Some daemons (Hyprland) regenerate their
# config between cleanup and the dry-run, so a flagged conflict here doesn't
# mean stow will actually fail — cleanup_autogenerated runs again right before
# stow, closing the race. Only abort on conflicts we don't know how to clean.
if grep -q "cannot stow\|existing target\|conflicts" /tmp/stow_dryrun.log; then
    echo ""
    echo "⚠️  Dry-run flagged potential conflicts (will retry cleanup before stow):"
    grep -v "WARNING: in simulation mode" /tmp/stow_dryrun.log

    # Anything flagged that's NOT a known auto-generated file is a real conflict.
    UNKNOWN_CONFLICTS=$(grep -oE "existing target [^ ]+" /tmp/stow_dryrun.log \
        | awk '{print $3}' \
        | grep -vE '^\.config/hypr/hyprland\.conf$|^\.gitconfig$|^\.config/mimeapps\.list$' \
        || true)
    if [ -n "$UNKNOWN_CONFLICTS" ]; then
        echo ""
        echo "❌ Unknown conflicts that aren't in the auto-generated list:"
        echo "$UNKNOWN_CONFLICTS"
        echo ""
        echo "Options to resolve:"
        echo "  1. Manually remove/backup the conflicting files listed above"
        echo "  2. Run: cd ~/dotfiles && stow --adopt -t ~ ."
        echo "     (This moves existing files INTO your dotfiles repo - review with git diff after)"
        echo "  3. Add the conflicting files to cleanup_autogenerated() in this script"
        exit 1
    fi
    echo "  (all flagged files are handled by cleanup_autogenerated — continuing)"
else
    echo "✓ No conflicts detected"
fi

# ============================================================================
# Step 3: Actually Link with Stow (Safe Restow)
# ============================================================================
echo ""
echo "🔗 Linking dotfiles with stow..."

# Retry loop: Hyprland watches its config and regenerates it the moment it's
# deleted, so even cleanup-then-stow can race. We retry a few times — each
# attempt has a fresh, vanishingly small window between cleanup and stow.
# pipefail is required so we see stow's exit code through `tee`.
set -o pipefail
stow_ok=0
for attempt in 1 2 3 4 5; do
    cleanup_autogenerated
    if stow --restow -t ~ . 2>&1 | tee /tmp/stow_output.log; then
        if ! grep -q "All operations aborted\|cannot stow" /tmp/stow_output.log; then
            stow_ok=1
            break
        fi
    fi
    echo "  → stow attempt $attempt hit a race, retrying..."
done
set +o pipefail

if [ "$stow_ok" -ne 1 ]; then
    echo ""
    echo "❌ ERROR: Stow failed after retries! See /tmp/stow_output.log."
    echo ""
    echo "Common issues:"
    echo "  - A program created a real file where a symlink should be"
    echo "  - Add the file to cleanup_autogenerated() in this script"
    echo "  - Or use: stow --adopt -t ~ . (then review with git diff)"
    exit 1
fi

echo "✓ Dotfiles linked successfully!"

# ============================================================================
# Step 4: Setup Host-Specific Configs
# ============================================================================
echo ""
echo "🖥️  Setting up host-specific configs..."

HOSTNAME=$(cat /etc/hostname)
HYPR_HOSTS_DIR="$HOME/.config/hypr/hosts"

if [ -f "$HYPR_HOSTS_DIR/$HOSTNAME.conf" ]; then
    ln -sf "$HOSTNAME.conf" "$HYPR_HOSTS_DIR/current.conf"
    echo "  ✓ Hyprland host config linked: $HOSTNAME"
else
    echo "  ⚠ No host config found for '$HOSTNAME'"
    echo "    Create one at: $HYPR_HOSTS_DIR/$HOSTNAME.conf"
    echo "    (You can copy from an existing host config)"
fi

# Link host-specific hypridle config
if [ -f "$HYPR_HOSTS_DIR/hypridle-$HOSTNAME.conf" ]; then
    ln -sf "$HYPR_HOSTS_DIR/hypridle-$HOSTNAME.conf" "$HOME/.config/hypr/hypridle.conf"
    echo "  ✓ Hypridle config linked: $HOSTNAME (host-specific)"
else
    echo "  ⚠ No hypridle config found for '$HOSTNAME', using default"
fi

# ============================================================================
# Step 5: Fix Permissions & Reload Configs
# ============================================================================
echo ""
echo "🔧 Fixing permissions and reloading configs..."

# Fix SSH directory permissions (required by SSH)
if [ -d "$HOME/.ssh" ]; then
    chmod 700 "$HOME/.ssh"
    [ -f "$HOME/.ssh/config" ] && chmod 600 "$HOME/.ssh/config"
    [ -f "$HOME/.ssh/known_hosts" ] && chmod 600 "$HOME/.ssh/known_hosts"
    echo "  ✓ SSH permissions fixed (700 for dir, 600 for files)"
fi

# Reload tmux config if tmux is running
if command -v tmux &> /dev/null && tmux list-sessions &> /dev/null 2>&1; then
    tmux source-file ~/.tmux.conf 2>/dev/null && echo "  ✓ Tmux config reloaded"
fi

# Reload Hyprland if running
if pgrep -x Hyprland > /dev/null; then
    hyprctl reload > /dev/null 2>&1 && echo "  ✓ Hyprland config reloaded"
fi

# ============================================================================
# Step 6: Setup Theme Switcher
# ============================================================================
echo ""
echo "🎨 Setting up theme switcher..."

THEME_SWITCHER_DIR="$HOME/projects/theme-switcher"

# Symlink theme-switch to PATH
if [ -x "$THEME_SWITCHER_DIR/scripts/theme-switch" ]; then
    mkdir -p "$HOME/.local/bin"
    ln -sf "$THEME_SWITCHER_DIR/scripts/theme-switch" "$HOME/.local/bin/theme-switch"
    echo "  ✓ theme-switch linked to ~/.local/bin/"
else
    echo "  ⚠ theme-switcher not found at $THEME_SWITCHER_DIR"
    echo "    Clone it: git clone https://github.com/StephenGunn/theme-switcher.git $THEME_SWITCHER_DIR"
fi

# Apply a default theme if none is set (fresh install)
if [ ! -f "$HOME/.config/current-theme" ]; then
    echo "  ⚠ No theme set (fresh install detected)"
    if [ -x "$HOME/.local/bin/theme-switch" ]; then
        echo "  → Applying default theme: gruvbox-dark"
        "$HOME/.local/bin/theme-switch" gruvbox-dark > /dev/null 2>&1 && \
            echo "  ✓ Default theme applied" || \
            echo "  ⚠ Failed to apply default theme (run 'theme-switch' manually)"
    fi
fi

echo ""
echo "🎉 Done! Your dotfiles are linked and ready."
