// Auto-generated by theme-switcher - do not edit manually
pragma Singleton
import QtQuick

QtObject {
    // Base colors
    readonly property color background: "#1d2021"
    readonly property color backgroundLight: "#282828"
    readonly property color foreground: "#ebdbb2"
    readonly property color foregroundDim: "#a89984"

    // Accent colors
    readonly property color accent: "#d79921"
    readonly property color accentBright: "#fabd2f"

    // Semantic colors
    readonly property color red: "#cc241d"
    readonly property color green: "#98971a"
    readonly property color yellow: "#d79921"
    readonly property color blue: "#458588"
    readonly property color magenta: "#b16286"
    readonly property color cyan: "#689d6a"

    // Bright variants
    readonly property color redBright: "#fb4934"
    readonly property color greenBright: "#b8bb26"
    readonly property color yellowBright: "#fabd2f"
    readonly property color blueBright: "#83a598"
    readonly property color magentaBright: "#d3869b"
    readonly property color cyanBright: "#8ec07c"

    // UI specific
    readonly property color separator: "#504945"
    readonly property color workspaceActive: "#fabd2f"
    readonly property color workspaceOccupied: "#83a598"
    readonly property color workspaceEmpty: "#504945"

    // Font
    readonly property string fontFamily: "JetBrainsMono Nerd Font Mono"
}
