// Auto-generated by theme-switcher - do not edit manually
pragma Singleton
import QtQuick

QtObject {
    // Base colors
    readonly property color background: "#1f1f28"
    readonly property color backgroundLight: "#2a2a37"
    readonly property color foreground: "#dcd7ba"
    readonly property color foregroundDim: "#727169"

    // Accent colors
    readonly property color accent: "#e6c384"
    readonly property color accentBright: "#e6c384"

    // Semantic colors
    readonly property color red: "#c34043"
    readonly property color green: "#76946a"
    readonly property color yellow: "#e6c384"
    readonly property color blue: "#7e9cd8"
    readonly property color magenta: "#957fb8"
    readonly property color cyan: "#7fb4ca"

    // Bright variants
    readonly property color redBright: "#e82424"
    readonly property color greenBright: "#98bb6c"
    readonly property color yellowBright: "#ff9e3b"
    readonly property color blueBright: "#7fb4ca"
    readonly property color magentaBright: "#938aa9"
    readonly property color cyanBright: "#7aa89f"

    // UI specific
    readonly property color separator: "#2a2a37"
    readonly property color workspaceActive: "#7e9cd8"
    readonly property color workspaceOccupied: "#957fb8"
    readonly property color workspaceEmpty: "#3a3a4d"

    // Font
    readonly property string fontFamily: "JetBrainsMono Nerd Font Mono"
}
