# Hypridle config for titan (laptop)

general {
    after_sleep_cmd = sh ~/.config/hypr/scripts/restore-after-wake.sh
}

# Dim display after 16.5 minutes
listener {
    timeout = 1000
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Keyboard backlight
listener {
    timeout = 1500
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Turn off display after 41 minutes
listener {
    timeout = 2500
    on-timeout = hyprctl dispatch dpms off && touch /tmp/display-off
    on-resume = hyprctl dispatch dpms on && rm -f /tmp/display-off
}

# Suspend after 50 minutes
listener {
    timeout = 3000
    on-timeout = systemctl suspend
}
