#!/bin/bash
# Toggle streaming mode on/off
# Creates a sidebar with webcams and widget

STATE_FILE="/tmp/streaming-mode-active"
WIDGET_FILE="/tmp/streaming-widget"
CONFIG="$HOME/.config/streaming/config.sh"
STREAMING_CONF="$HOME/.config/hypr/streaming.conf"

# Load config
if [[ -f "$CONFIG" ]]; then
    source "$CONFIG"
else
    echo "Config not found: $CONFIG"
    exit 1
fi

# Default widget if not set
WIDGET="${WIDGET:-bonsai}"

# Write streaming workspace gaps to config file
# This survives hyprctl reload
write_streaming_config() {
    local enabled="$1"

    if [[ "$enabled" == "on" ]]; then
        cat > "$STREAMING_CONF" <<EOF
# Streaming mode workspace gaps
# This file is auto-generated by streaming-mode.sh
# DO NOT EDIT MANUALLY

workspace = 1, gapsout:20 ${SIDEBAR_WIDTH} 20 20
workspace = 2, gapsout:20 ${SIDEBAR_WIDTH} 20 20
workspace = 3, gapsout:20 ${SIDEBAR_WIDTH} 20 20
workspace = 4, gapsout:20 ${SIDEBAR_WIDTH} 20 20
workspace = 5, gapsout:20 ${SIDEBAR_WIDTH} 20 20
EOF
    else
        cat > "$STREAMING_CONF" <<EOF
# Streaming mode workspace gaps
# This file is auto-generated by streaming-mode.sh
# DO NOT EDIT MANUALLY

# Streaming mode is OFF - default gaps
EOF
    fi
}

# Apply workspace gaps immediately (for instant feedback)
apply_gaps() {
    local enabled="$1"

    if [[ "$enabled" == "on" ]]; then
        hyprctl --batch "\
            keyword workspace 1,gapsout:20 ${SIDEBAR_WIDTH} 20 20; \
            keyword workspace 2,gapsout:20 ${SIDEBAR_WIDTH} 20 20; \
            keyword workspace 3,gapsout:20 ${SIDEBAR_WIDTH} 20 20; \
            keyword workspace 4,gapsout:20 ${SIDEBAR_WIDTH} 20 20; \
            keyword workspace 5,gapsout:20 ${SIDEBAR_WIDTH} 20 20"
    else
        hyprctl --batch "\
            keyword workspace 1,gapsout:20 20 20 20; \
            keyword workspace 2,gapsout:20 20 20 20; \
            keyword workspace 3,gapsout:20 20 20 20; \
            keyword workspace 4,gapsout:20 20 20 20; \
            keyword workspace 5,gapsout:20 20 20 20"
    fi
}

# Check if OBS is running (cameras would be in use)
check_obs() {
    if pgrep -x "obs" > /dev/null; then
        notify-send "Streaming Mode" "Cannot enable - OBS is running and using cameras" -u critical
        echo "Error: OBS is running. Close OBS first or use OBS for streaming instead."
        exit 1
    fi
}

# Build mpv command with low-latency settings
# Position/size handled by Hyprland window rules
mpv_webcam() {
    local device="$1"
    local title="$2"

    mpv --profile=low-latency \
        --untimed \
        --no-cache \
        --demuxer-lavf-o=fflags=+nobuffer \
        --demuxer-lavf-analyzeduration=0 \
        --demuxer-lavf-probesize=32 \
        --demuxer-lavf-o=input_format=${MPV_FORMAT},video_size=${MPV_RESOLUTION},framerate=${MPV_FRAMERATE} \
        --msg-level=ffmpeg=error \
        --no-osc --no-border --no-input-default-bindings \
        --title="$title" \
        "av://v4l2:$device" &
}

streaming_on() {
    # Check for OBS first
    check_obs

    # Write config file (survives hyprctl reload)
    write_streaming_config "on"

    # Apply gaps immediately
    apply_gaps "on"

    # Small delay for layout to adjust
    sleep 0.2

    # Launch keystroke display (if screenkey is installed)
    if command -v screenkey &> /dev/null; then
        screenkey --position fixed \
                  --geometry "${WEBCAM_WIDTH}x${KEYS_HEIGHT}+${SIDEBAR_X}+${KEYS_Y}" \
                  --font-size medium \
                  --timeout 3 \
                  --no-systray &
    fi

    # Launch face webcam (window rules handle position/size/pin)
    if [[ -e "$CAM_FACE" ]]; then
        mpv_webcam "$CAM_FACE" "webcam-face"
    fi

    # Launch top-down webcam (window rules handle position/size/pin)
    if [[ -e "$CAM_TOPDOWN" ]]; then
        mpv_webcam "$CAM_TOPDOWN" "webcam-topdown"
    fi

    # Launch default widget
    launch_widget "$WIDGET"

    # Mark as active
    touch "$STATE_FILE"
}

streaming_off() {
    # Kill streaming windows
    pkill -f "screenkey" 2>/dev/null
    pkill -f "mpv.*webcam" 2>/dev/null
    kill_widget

    # Write config file (survives hyprctl reload)
    write_streaming_config "off"

    # Apply gaps immediately
    apply_gaps "off"

    # Remove state files
    rm -f "$STATE_FILE" "$WIDGET_FILE"
}

# Restart just the webcam windows (keep gaps)
restart_cams() {
    pkill -f "mpv.*webcam" 2>/dev/null
    sleep 0.3

    if [[ -e "$CAM_FACE" ]]; then
        mpv_webcam "$CAM_FACE" "webcam-face"
    fi
    if [[ -e "$CAM_TOPDOWN" ]]; then
        mpv_webcam "$CAM_TOPDOWN" "webcam-topdown"
    fi
}

# Kill current widget by window title (more precise than pkill -f)
kill_widget() {
    hyprctl clients -j | jq -r '.[] | select(.title | startswith("streaming-")) | .pid' 2>/dev/null | while read pid; do
        [[ -n "$pid" ]] && kill "$pid" 2>/dev/null
    done
}

# Launch a widget in the bottom slot
launch_widget() {
    local widget="${1:-bonsai}"

    kill_widget
    sleep 0.2

    case "$widget" in
        bonsai)
            ghostty --title="streaming-bonsai" -e cbonsai -l -t 0.15 -i &
            ;;
        cmatrix)
            ghostty --title="streaming-cmatrix" -e cmatrix -b -s &
            ;;
        cava)
            ghostty --title="streaming-cava" -e cava &
            ;;
        pipes)
            ghostty --title="streaming-pipes" -e pipes.sh &
            ;;
        none)
            # Just kill, don't launch anything
            ;;
        *)
            echo "Unknown widget: $widget"
            echo "Available: bonsai, cmatrix, cava, pipes, none"
            return 1
            ;;
    esac

    echo "$widget" > "$WIDGET_FILE"
}

# Swap to a different widget
swap_widget() {
    local widget="$1"
    if [[ ! -f "$STATE_FILE" ]]; then
        echo "Streaming mode not active"
        return 1
    fi
    launch_widget "$widget"
}

# Restore gaps after config reload (e.g., theme switch)
# Since streaming.conf is sourced by hyprland.conf, gaps should persist
# This is mainly for ensuring config file is correct
restore_gaps() {
    if [[ ! -f "$STATE_FILE" ]]; then
        return 0  # Not active, nothing to restore
    fi

    # Ensure config file has streaming gaps
    write_streaming_config "on"
}

# Handle arguments
case "${1:-toggle}" in
    on)
        streaming_on
        ;;
    off)
        streaming_off
        ;;
    toggle)
        if [[ -f "$STATE_FILE" ]]; then
            streaming_off
        else
            streaming_on
        fi
        ;;
    restart|refresh)
        restart_cams
        ;;
    widget)
        swap_widget "$2"
        ;;
    restore)
        restore_gaps
        ;;
    status)
        if [[ -f "$STATE_FILE" ]]; then
            echo "Streaming mode: ON"
            [[ -f "$WIDGET_FILE" ]] && echo "Widget: $(cat "$WIDGET_FILE")"
            exit 0
        else
            echo "Streaming mode: OFF"
            exit 1
        fi
        ;;
    *)
        echo "Usage: streaming-mode.sh [on|off|toggle|restart|widget <name>|status]"
        echo "Widgets: bonsai, cmatrix, cava, pipes, none"
        exit 1
        ;;
esac
