#!/bin/bash
# Toggle streaming mode on/off
# Creates a sidebar gap for camera windows and launches widgets
# Camera windows (e.g. OBS projector) are placed manually in the sidebar area

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
STATE_FILE="/tmp/streaming-mode-active"
WIDGET_FILE="/tmp/streaming-widget"
CONFIG="$HOME/.config/streaming/config.sh"
STREAMING_CONF="$HOME/.config/hypr/streaming_gen.lua"

# Load config
if [[ -f "$CONFIG" ]]; then
    source "$CONFIG"
else
    echo "Config not found: $CONFIG"
    exit 1
fi

# Default widget if not set
WIDGET="${WIDGET:-bonsai}"

# Write streaming workspace gaps to config file
# This survives hyprctl reload
write_streaming_config() {
    local enabled="$1"

    if [[ "$enabled" == "on" ]]; then
        cat > "$STREAMING_CONF" <<HEADER
-- Streaming mode workspace gaps
-- This file is auto-generated by streaming-mode.sh
-- DO NOT EDIT MANUALLY
HEADER
        for ws in $STREAMING_WORKSPACES; do
            echo "hl.workspace_rule({ workspace = \"$ws\", monitor = \"${MONITOR}\", gaps_out = { top = 15, right = ${SIDEBAR_WIDTH}, bottom = 15, left = 15 } })" >> "$STREAMING_CONF"
        done
    else
        cat > "$STREAMING_CONF" <<EOF
-- Streaming mode workspace gaps
-- This file is auto-generated by streaming-mode.sh
-- DO NOT EDIT MANUALLY

-- Streaming mode is OFF - default gaps
EOF
    fi
}

# Apply workspace gaps immediately via Lua eval API
apply_gaps() {
    local enabled="$1"

    if [[ "$enabled" == "on" ]]; then
        local right="${SIDEBAR_WIDTH}"
    else
        local right=15
    fi

    for ws in $STREAMING_WORKSPACES; do
        hyprctl eval "hl.workspace_rule({ workspace = \"$ws\", monitor = \"${MONITOR}\", gaps_out = { top = 15, right = $right, bottom = 15, left = 15 } })"
    done
}

# Move scratchpad to streaming position (left of sidebar)
move_scratchpad() {
    local scratchpad_addr=$(hyprctl clients -j | jq -r '.[] | select(.workspace.name == "special:magic") | .address')
    if [[ -n "$scratchpad_addr" ]]; then
        hyprctl dispatch movewindowpixel exact 100 100,address:$scratchpad_addr
    fi
}

streaming_on() {
    # Write config file (survives hyprctl reload)
    write_streaming_config "on"

    # Apply gaps immediately
    apply_gaps "on"

    # Small delay for layout to adjust
    sleep 0.2

    # Launch keystroke display (if screenkey is installed)
    if command -v screenkey &> /dev/null; then
        screenkey --position fixed \
                  --geometry "${WEBCAM_WIDTH}x${KEYS_HEIGHT}+${SIDEBAR_X}+${KEYS_Y}" \
                  --font-size medium \
                  --timeout 3 \
                  --no-systray &
    fi

    # Launch default widget
    launch_widget "$WIDGET"

    # Move scratchpad if it exists
    move_scratchpad

    # Start sidebar daemon (repositions windows after workspace switches)
    pkill -f "streaming-scratchpad-daemon.sh" 2>/dev/null
    "$SCRIPT_DIR/streaming-scratchpad-daemon.sh" start &

    # Mark as active
    touch "$STATE_FILE"

    notify-send "Streaming Mode" "ON — place camera windows in sidebar" -t 2000
}

streaming_off() {
    # Kill sidebar daemon
    pkill -f "streaming-scratchpad-daemon.sh" 2>/dev/null

    # Kill streaming windows
    pkill -f "screenkey" 2>/dev/null
    kill_widget

    # Write config file (survives hyprctl reload)
    write_streaming_config "off"

    # Apply gaps immediately
    apply_gaps "off"

    # Remove state files
    rm -f "$STATE_FILE" "$WIDGET_FILE"
    rm -f /tmp/streaming-cams-hidden 2>/dev/null
    rm -f /tmp/streaming-blur-active 2>/dev/null

    notify-send "Streaming Mode" "OFF" -t 1500
}

# Kill current widget by window title (more precise than pkill -f)
kill_widget() {
    hyprctl clients -j | jq -r '.[] | select(.title | startswith("streaming-")) | .pid' 2>/dev/null | while read pid; do
        [[ -n "$pid" ]] && kill "$pid" 2>/dev/null
    done
}

# Launch a widget in the bottom slot
launch_widget() {
    local widget="${1:-bonsai}"

    kill_widget
    sleep 0.2

    case "$widget" in
        bonsai)
            ghostty --title="streaming-bonsai" -e cbonsai -l -t 0.15 -i &
            ;;
        cmatrix)
            ghostty --title="streaming-cmatrix" -e cmatrix -b -s &
            ;;
        cava)
            ghostty --title="streaming-cava" -e cava &
            ;;
        pipes)
            ghostty --title="streaming-pipes" -e pipes.sh &
            ;;
        none)
            # Just kill, don't launch anything
            ;;
        *)
            echo "Unknown widget: $widget"
            echo "Available: bonsai, cmatrix, cava, pipes, none"
            return 1
            ;;
    esac

    echo "$widget" > "$WIDGET_FILE"
}

# Swap to a different widget
swap_widget() {
    local widget="$1"
    if [[ ! -f "$STATE_FILE" ]]; then
        echo "Streaming mode not active"
        return 1
    fi
    launch_widget "$widget"
}

# Restore gaps after config reload (e.g., theme switch)
restore_gaps() {
    if [[ ! -f "$STATE_FILE" ]]; then
        return 0
    fi
    write_streaming_config "on"
}

# Handle arguments
case "${1:-toggle}" in
    on)
        streaming_on
        ;;
    off)
        streaming_off
        ;;
    toggle)
        if [[ -f "$STATE_FILE" ]]; then
            streaming_off
        else
            streaming_on
        fi
        ;;
    widget)
        swap_widget "$2"
        ;;
    restore)
        restore_gaps
        ;;
    status)
        if [[ -f "$STATE_FILE" ]]; then
            echo "Streaming mode: ON"
            [[ -f "$WIDGET_FILE" ]] && echo "Widget: $(cat "$WIDGET_FILE")"
            exit 0
        else
            echo "Streaming mode: OFF"
            exit 1
        fi
        ;;
    *)
        echo "Usage: streaming-mode.sh [on|off|toggle|widget <name>|restore|status]"
        echo "Widgets: bonsai, cmatrix, cava, pipes, none"
        exit 1
        ;;
esac
