return {
	"xiyaowong/transparent.nvim",
	config = function()
		require("transparent").setup({
			-- Enable transparency globally
			enable = true,
			-- Exclude specific highlight groups from being made transparent
			extra_groups = {
				-- BufferLine - keep all elements opaque with solid theme colors
				"BufferLineFill",
				"BufferLineBackground",
				"BufferLineBuffer",
				"BufferLineBufferSelected",
				"BufferLineBufferVisible",
				"BufferLineModified",
				"BufferLineModifiedSelected",
				"BufferLineModifiedVisible",
				"BufferLineNumbers",
				"BufferLineNumbersVisible",
				"BufferLineNumbersSelected",
				"BufferLineTab",
				"BufferLineTabSelected",
				"BufferLineTabClose",
				"BufferLineCloseButton",
				"BufferLineCloseButtonVisible",
				"BufferLineCloseButtonSelected",
				"BufferLineSeparator",
				"BufferLineSeparatorVisible",
				"BufferLineSeparatorSelected",
				"BufferLineIndicatorVisible",
				"BufferLineIndicatorSelected",
				"BufferLineDuplicate",
				"BufferLineDuplicateVisible",
				"BufferLineDuplicateSelected",
				"BufferLinePick",
				"BufferLinePickVisible",
				"BufferLinePickSelected",
				-- BufferLine diagnostics
				"BufferLineError",
				"BufferLineErrorVisible",
				"BufferLineErrorSelected",
				"BufferLineErrorDiagnostic",
				"BufferLineErrorDiagnosticVisible",
				"BufferLineErrorDiagnosticSelected",
				"BufferLineWarning",
				"BufferLineWarningVisible",
				"BufferLineWarningSelected",
				"BufferLineWarningDiagnostic",
				"BufferLineWarningDiagnosticVisible",
				"BufferLineWarningDiagnosticSelected",
				"BufferLineInfo",
				"BufferLineInfoVisible",
				"BufferLineInfoSelected",
				"BufferLineInfoDiagnostic",
				"BufferLineInfoDiagnosticVisible",
				"BufferLineInfoDiagnosticSelected",
				"BufferLineHint",
				"BufferLineHintVisible",
				"BufferLineHintSelected",
				"BufferLineHintDiagnostic",
				"BufferLineHintDiagnosticVisible",
				"BufferLineHintDiagnosticSelected",
				"BufferLineDiagnostic",
				"BufferLineDiagnosticVisible",
				"BufferLineDiagnosticSelected",
			},
			-- You can also exclude other parts if needed:
			exclude = {},
		})
	end,
}
