import = [
    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
]

[font]
size = 14.5

[font.normal]
family = "JetBrainsMono Nerd Font"

[shell]
program = "/bin/zsh"

[window.padding]
x = 10
y = 10
