import = [
    # "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
# uncomment the flavour you want below:
    # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]
[env]
TERM = "xterm-256color"

[font]
size = 15

[font.normal]
family = "JetBrainsMono Nerd Font"

[shell]
args = ['-l', '-c', 'tmux attach || tmux']
program = "/bin/zsh"

[window]
opacity = 0.95

[window.padding]
x = 5 
y = 5 
